### ISSUE TITLE
Linking with 'cc' failed

### ISSUE THREAD

**Issue by ToriTyler** [rust-ndarray/ndarray-linalg#171]
Hi everyone,

I'm a total rookie and I encountered a problem when using ```ndarray-linalg```.

I wrote a script that has a ```main``` function in rust, and in the ```Cargo.toml``` file, I included a local dependency which uses ```ndarray-linalg``` to do SVD decomposition.

```
[dependencies]
the_local_dependency = { path = "/home/tori/Documents/VSCode/rust-proj-test/the_local_dependency" }
failure = "0.1"
stdinout = "0.4"
rand = "0.6"
rand_xorshift = "0.1"
reductive = "0.2"
```

Here is the .toml file of the local dependency:

```
ndarray = "0.12"
ndarray-linalg = "0.11.0"
ordered-float = "1"
rand = "0.6"
rand_xorshift = "0.1"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
```

And when I ```cargo run``` the ```main.rs```, the following error message shows up:
```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/tori/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" 
...
```
and 
```
= note: /home/tori/Documents/VSCode/rust-proj-test/prune/target/debug/deps/prune-b3f2f510d4e3b942.2w4umcyk6v9wp1jo.rcgu.o: In function `ndarray::linalg::impl_linalg::<impl ndarray::ArrayBase<S,ndarray::dimension::dim::Dim<[usize; _]>>>::dot_impl':
          /home/tori/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.12.1/src/linalg/impl_linalg.rs:115: undefined reference to `cblas_sdot'
          /home/tori/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.12.1/src/linalg/impl_linalg.rs:115: undefined reference to `cblas_ddot'
          /home/tori/Documents/VSCode/rust-proj-test/prune/target/debug/deps/libfinalfusion-66cb19c0220bd3c0.rlib(finalfusion-66cb19c0220bd3c0.3jimcmdkcxeluct4.rcgu.o): In function `ndarray::linalg::impl_linalg::mat_mul_impl':
          /home/tori/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.12.1/src/linalg/impl_linalg.rs:422: undefined reference to `cblas_sgemm'
          /home/tori/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.12.1/src/linalg/impl_linalg.rs:422: undefined reference to `cblas_dgemm'
          /home/tori/Documents/VSCode/rust-proj-test/prune/target/debug/deps/libndarray_linalg-b06c2b355829db2f.rlib(ndarray_linalg-b06c2b355829db2f.ndarray_linalg.dokuf6fj-cgu.1.rcgu.o): In function `lapacke::sgesvd':
          /home/tori/.cargo/registry/src/github.com-1ecc6299db9ec823/lapacke-0.2.0/src/lib.rs:5195: undefined reference to `LAPACKE_sgesvd'
          collect2: error: ld returned 1 exit status
```

I have installed openBLAS via ```sudo apt-get install libopenblas-dev```, as well as ```gfortran```, and I'm using Ubuntu 18.0

I tried the same thing on Windows10, and got an error like:
```
error: Linking with 'link.exe' failed: exit code:1120
```

Please help me! Thank you!

Sincerely,
Tori

**Comment by jturner314** [comment]
It looks like you need to link to a backend crate. There are a few ways to do this.

One way is to specify the backend in the final binary crate. For example, to specify the OpenBLAS backend in your final crate, add the following dependency:

```toml
# final crate
openblas-src = "0.7"
```

and add

```rust
// final crate
extern crate openblas_src;
```

to your `lib.rs`.

An alternative option is to change the `ndarray-linalg` dependency in your local dependency to

```toml
# local dependency crate
ndarray-linalg = { version = "0.11", features = ["openblas"] }
```

but the disadvantage is that it restricts the final binary crate to the OpenBLAS backend.

Perhaps the most convenient option from the perspective of the final crate would be for you to add the following to the `Cargo.toml` of your local dependency:

```toml
# local dependency crate
[features]
openblas = ["ndarray-linalg/openblas"]
netlib = ["ndarray-linalg/netlib"]
intel-mkl = ["ndarray-linalg/intel-mkl"]
```

(In other words, the `openblas` feature in the local dependency enables the `openblas` feature on its `ndarray-linalg` dependency.) Then, in the final binary crate, specify the feature corresponding to the desired backend:

```toml
# final crate
the_local_dependency = { path = "/home/tori/Documents/VSCode/rust-proj-test/the_local_dependency", features = ["openblas"] }
```

See the [README](https://github.com/rust-ndarray/ndarray-linalg#blaslapack-backend) for details.

**Comment by rspeer** [comment]
I tried following these directions, such as adding `features = ["openblas"]` or adding a dependency on `openblas-src = "0.7"`, but both those seem to depend on the `openblas-src` crate which requires some unspecified source archive of OpenBLAS.

Is there a way to link to the OpenBLAS I already have via Ubuntu?

**Comment by felix-clark** [comment]
I also experienced linking failures (in Ubuntu 18) trying to follow the README and the suggestion above by @jturner314 . I ended up solving them by using `features = ["openblas-src"]` (as opposed to `"openblas"`) in the `ndarray-linalg` line of my package's `Cargo.toml` and also removing the explicit dependence on the separate `openblas-src` crate.

If this is expected/intended, perhaps the instructions could be updated? Otherwise, hopefully this approach could help others in this thread.

**Comment by jturner314** [comment]
@rspeer I think it should be possible to use the system OpenBLAS by explicitly depending on the `openblas-src` crate and enabling the `system` feature:

```toml
[dependencies]
ndarray = "0.13"
ndarray-linalg = "0.12"
blas-src = { version = "0.4.0", default-features = false, features = ["openblas"] }
lapack-src = { version = "0.4.0", default-features = false, features = ["openblas"] }
openblas-src = { version = "0.7", features = ["system"] }
```

(See the `openblas-src` [README](https://github.com/blas-lapack-rs/openblas-src).)

@felix-clark I'm surprised changing `features = ["openblas"]` to `features = ["openblas-src"]` fixed a linker problem. To clarify, I assume you were trying the following:

```toml
[dependencies]
ndarray = "0.13"
ndarray-linalg = { version = "0.12", features = ["openblas"] }
``` 

Will you please post the relevant portion of your `Cargo.toml` and the error message you received?

**Comment by felix-clark** [comment]
@jturner314 I did my best to make a minimal recreation of the issues I was facing.

I made a library crate with a test function that just calls `solve()` for a test matrix and vector (i.e. Array2 and Array1). That corresponding Cargo.toml has the following:
```
[features]
openblas = ["ndarray-linalg/openblas"]
openblas-src = ["ndarray-linalg/openblas-src"]

[dependencies]
ndarray = { version = "0.13.0", features = ["blas"] }
ndarray-linalg = { version = "0.12.0" }
```

In a separate binary crate I depend on this library and call the test function in `main()`. Based on the instructions I would have expected this `Cargo.toml` to work:
```
[dependencies]
library = { path = "../library" }
openblas-src = { version = "0.7.0", features = ["system"] }
lapack-src = { version = "0.4.0", default-features = false, features = ["openblas"] }
```
however this build fails with linking errors such as `undefined reference to 'LAPACKE_sgetrf'`. Activating the "openblas" feature of my library crate using instead `library = { path = "../library", features = ["openblas"] }` results in similar issues if I keep the explicit `openblas-src` dependency. If I remove the explicit `openblas-src` dependency, so that the binary's `Cargo.toml` dependencies looks like this:
```
library = { path = "../library", features = ["openblas"] }
lapack-src = { version = "0.4.0", default-features = false, features = ["openblas"] }
```
then I can actually build and run using cargo. However, trying to run the standalone binary in `target/` results in this error: `target/debug/binary: symbol lookup error: target/debug/binary: undefined symbol: LAPACKE_sgetrs`. This is the issue I can resolve by changing from `openblas` to the `openblas-src` feature.

In the end my binary crate works as a standalone if I have this:
```
[dependencies]
library = { path = "../library", features = ["openblas-src"] }
lapack-src = { version = "0.4.0", default-features = false, features = ["openblas"] }
```
with the library `Cargo.toml` listed above.

**Comment by rspeer** [comment]
@jturner314 I can't currently compile rust-ndarray for a more basic reason, a version conflict with ndarray.

Here's the Cargo.toml I'm currently trying to use:

```
[dependencies]
numpy = "0.7.0"
ndarray = "0.13"
ndarray-linalg = "0.12"
blas-src = { version = "0.4.0", default-features = false, features = ["openblas"] }
lapack-src = { version = "0.4.0", default-features = false, features = ["openblas"] }
openblas-src = { version = "0.7", features = ["system"] }
rand_pcg = "0.2.1"
rand = "0.7.2"
ndarray-rand = "*"
assert_approx_eq = "1.1.0"
```

This won't compile because ndarray-linalg 0.12 has a dependency on `ndarray = "^0.12.0"`. Even if I change the ndarray requirement, it conflicts with other libraries that also expect ndarray 0.13, which I can't track down.

**Comment by rspeer** [comment]
Here's a simpler Cargo.toml where I try to start over and do just what the README says:

```
[dependencies]
numpy = "0.7.0"
ndarray = "0.13"
ndarray-linalg = { version = "0.12", features = ["openblas"] }
rand_pcg = "0.2.1"
rand = "0.7.2"
ndarray-rand = "0.10"  # outdated
assert_approx_eq = "1.1.0"
```

After `cargo clean` and `cargo build`, the error I get is:

```
error: failed to run custom build command for `openblas-src v0.7.0`

Caused by:
  process didn't exit successfully: `/home/rspeer/code/skipgram-engine/target/debug/build/openblas-src-1acb45e3d7ad0634/build-script-build` (exit code: 101)
--- stdout
Running: `"make" "libs" "netlib" "shared" "BINARY=64" "YES_CBLAS=1" "YES_LAPACKE=1" "-j12"`

--- stderr
Makefile.system:47: Makefile.rule: No such file or directory
make: Makefile.prebuild: No such file or directory
make: *** No rule to make target 'Makefile.prebuild'.  Stop.
Makefile.system:195: Makefile.conf: No such file or directory
Makefile.system:1063: Makefile.: No such file or directory
make: *** No rule to make target 'Makefile.'.  Stop.
thread 'main' panicked at 'Failed: `"make" "libs" "netlib" "shared" "BINARY=64" "YES_CBLAS=1" "YES_LAPACKE=1" "-j12"` (exit code: 2)', /home/rspeer/.cargo/registry/src/github.com-1ecc6299db9ec823/openblas-src-0.7.0/build.rs:68:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by rhysnewell** [comment]
I'm having a very similar issue to this, however it is only occurring when trying to build on Travis CI. Every other machine I've tried manages to compile ndarray-linalg and openblas-src just fine. The gfortran package is installed and other essential build packages so really not sure what is going on.

**Comment by felix-clark** [comment]
@rhysnewell I was also struggling with the travis CI of a crate that depends on `ndarray-linalg`, and I was able to circumvent it by using the master branch of  `ndarray-linalg` along with `blas-src = "0.6"`. Of course I can't say for sure if that will fix your issue but it might be worth a try. And unfortunately I can't speak to the possibility of this addressing the original issue.

Regardless, it might be useful to publish a new tag of `ndarray-linalg` that uses the more recent tags of blas/openblas-src so that crates can be published with the latest dependencies.

**Comment by David-OConnor** [comment]
Also struggling on this. Using a Raspberry Pi. Is there an ELI-5 for getting this to work? Or a pre-compiled C libs. IME, expecting the user to compile C or fortran libs rarely works.

**Comment by termoshtt** [comment]
stacked question issue. close
