### ISSUE TITLE
Getting started on Raspberry Pi

### ISSUE THREAD

**Issue by David-OConnor** [rust-ndarray/ndarray-linalg#191]
Is there a tutorial on using this crate for people not experienced with linking C/Fortran? I've been getting errors on the Raspberry Pi; massive error dumps ending in:

```bash
61f3ebeba.ndarray_linalg.6xl29wmr-cgu.1.rcgu.o): in function `lapacke::sgetrf':
          /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/lapacke-0.2.0/src/lib.rs:6118: undefined reference to `LAPACKE_sgetrf'
          /usr/bin/ld: /home/pi/hydro/target/debug/deps/libndarray_linalg-b0315f161f3ebeba.rlib(ndarray_linalg-b0315f161f3ebeba.ndarray_linalg.6xl29wmr-cgu.1.rcgu.o): in function `lapacke::sgetrs':
          /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/lapacke-0.2.0/src/lib.rs:6277: undefined reference to `LAPACKE_sgetrs'
          collect2: error: ld returned 1 exit status

```

edit: Got it working on Windows with `intel-mkl` and no other steps

**Comment by termoshtt** [comment]
>  I've been getting errors on the Raspberry Pi

Raspberry Pi is working with ARMv8, and this crate is not supports ARM system currently. In theory, because [OpenBLAS supports ARM platforms](https://github.com/xianyi/OpenBLAS#arm64), `openblas` feature of this crate may works, however, I have never try it and will not work without some modification. I guess it will be hard "for people not experienced with linking C/Fortran".

**Comment by termoshtt** [comment]
Close this in flavor of #199
